---
title: "Lists and bootstrapping.Rmd"
author: "Yeyi Zhang"
date: "11/15/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rnoaa)
```

## R Markdown
```{r}

weather = 
  meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2016-01-01",
                      date_max = "2016-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```


```{r}
weather_nest = 
  weather %>% 
  nest(date:tmin)
```



```{r}
weather_nest

weather_nest$data
```

```{r}
weather_nest$data[[1]]

lm(tmax ~ tmin, data = weather_nest$data[[3]])

```


## Operation on list columns

write a function to fit tmax vs tmin for a given dataframe.

```{r}
weather_lm = function(df) {
  lm(tmax ~ tmin, data = df)
}
```

make sure this works ...

```{r}
weather_lm(weather_nest$data[[1]]) %>% broom::tidy()
```

can we loop or use a loop function ...

YES

```{r}
map(weather_nest$data, weather_lm)
```

Fit some models, and tidy the output

```{r}
weather_nest %>% 
  mutate(models = map(data, weather_lm),
         results = map(models, broom::tidy)) 

```

Add an unnest to see results

```{r}
weather_nest %>% 
  mutate(models = map(data, weather_lm),
         results = map(models, broom::tidy)) %>%
  select(-data, -models) %>%
  unnest()
```

## instacart data

```{r}
instacart = read_csv("./data/instacart_train_data.csv.zip")

instacart_nest = instacart %>% 
  group_by(department) %>% 
  nest() %>% 
  filter(department %in% c("deli", "produce", "snacks", "beverages"))

instacart_nest  

```

Let's try to summarize `order_hour_of_day`

```{r}
summary(instacart_nest$data[[1]]$order_hour_of_day)
```

do this using map

```{r}
instacart_nest %>% 
  mutate(summary = map(data, ~summary(.x[["order_hour_of_day"]])),
         results = map(summary, broom::tidy)) %>% 
  select(-data, -summary) %>% 
  unnest()
```

### Bootstrapping

```{r}

```
















